export enum EventTag {
  CONCERT     = 'CONCERT',
  SPORT       = 'SPORT',
  DANSE       = 'DANSE',
  CONCOURS    = 'CONCOURS',
  FEU_DARTIFICE = 'FEU_DARTIFICE',
  ENFANT      = 'ENFANT',
  FAMILLE     = 'FAMILLE',
  ADULTE      = 'ADULTE',
  TOUT_PUBLIC = 'TOUT_PUBLIC',
  PLEIN_AIR   = 'PLEIN_AIR',
  INTERIEUR   = 'INTERIEUR',
  MUSIQUE     = 'MUSIQUE',
  FESTIF      = 'FESTIF',
  CALME       = 'CALME',
  CULTUREL    = 'CULTUREL',
  RENCONTRE   = 'RENCONTRE',
  NETWORKING  = 'NETWORKING',
  JOUR        = 'JOUR',
  NUIT        = 'NUIT',
  FOOD        = 'FOOD',
  BOISSON     = 'BOISSON',
  DJ          = 'DJ',
  LIVE        = 'LIVE',
}
