// This file is auto-generated by scripts/generate-category-image-manifest.cjs
// Do not edit manually.

export const CATEGORY_FOLDER_FILES: Record<string, string[]> = {
  "ACTIVITES": [
    "activite2.png"
  ],
  "ARTS_EXPOS": [
    "art_expo2.png"
  ],
  "CULTURE_SPECTACLE": [
    "culture_spectacle2.png"
  ],
  "FAMILLE": [
    "famille2.png"
  ],
  "SORTIE": [
    "sortie2.png"
  ],
  "SPECIAL": [
    "special2.png"
  ],
  "VIE_LOCALE": [
    "vie_locale_2.png"
  ]
};
