// This file is auto-generated by scripts/generate-category-image-manifest.cjs
// Do not edit manually.

export const CATEGORY_FOLDER_FILES: Record<string, string[]> = {
  "ACTIVITES": [
    "reu1.png"
  ],
  "ARTS_EXPOS": [
    "expo1.png"
  ],
  "CULTURE_SPECTACLE": [
    "spec1.png"
  ],
  "FAMILLE": [],
  "SORTIE": [],
  "SPECIAL": [
    "autre1.png"
  ],
  "VIE_LOCALE": [
    "fest1.png"
  ]
};
